FROM python:3.9-slim-bullseye

RUN echo "srv_fastapi" > /etc/hostname

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get -yq install build-essential libglib2.0-dev pkg-config libpython3-dev libdbus-1-dev vim mc tree

# pick up user & grp ids
ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID app_user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID app_user

USER app_user
RUN mkdir -p /home/app_user/
WORKDIR /home/app_user/

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH "${PYTHONPATH}:/home/app_user/app"    

ENV PATH="/home/app_user/.local/bin:${PATH}"

COPY requirements.txt .
RUN pip3 install --upgrade pip && \
    pip3 install --user -r requirements.txt && \
    pip3 cache purge

RUN mkdir app
WORKDIR /home/app_user/app
COPY app/ .

EXPOSE 8000

# --------------------------------------
# CMD ["/bin/bash"]

CMD [ "uvicorn", "main_app:ep_obj","--host", "0.0.0.0", "--port","8000","--log-level", "debug", "--use-colors", "--reload" ]


